[versions]

# Android SDK
androidCompileSdk = "36"
androidMinSdk = "24"
androidNdk = "28.2.13676358"

# Build script
googleFirebaseCrashlyticsGradle = "3.0.6"
googleProtobufGradlePlugin = "0.9.6"
googleServices = "4.4.4"
androidGradlePlugin = "8.11.2"
java = "21"
kotlin = "2.2.0"
kotlinxCoroutines = "1.10.2"
ksp = "2.2.0-2.0.2"

# Androidx
androidxAnnotation = "1.9.1"
androidxAppCompat = "1.7.1"
androidxCardView = "1.0.0"
androidxConstraintLayout = "2.2.1"
androidxCoreKtx = "1.16.0"
androidxDatastore = "1.1.7"
androidxFragmentKtx = "1.8.8"
androidxLifecycle = "2.9.1"
androidxLifecycleExtension = "2.2.0"
androidxNavigation = "2.9.1"
androidxRecyclerView = "1.4.0"
androidxRoom = "2.7.2"
androidxSplashScreen = "1.0.1"
androidxVectorDrawable = "1.2.0"

# Other
airbnbLottie = "6.6.7"
googleMaterial = "1.12.0"
kotlinSerializationJson = "1.9.0"
openCv = "4.12.0"
googleDaggerHilt = "2.57.2"
googleProtobufRuntime = "4.33.2"

# PlayStore only
androidBillingClient = "8.0.0"
googleFirebaseBom = "33.16.0"
googleFirebaseCrashlytics = "19.4.4"
googleUserMessaging = "3.2.0"
googleGmsAds = "24.4.0"
googlePlayReview = "2.0.2"

# Tests only
androidxArchCoreTesting = "2.2.0"
androidxTestCore = "1.6.1"
androidxTestExtJunit = "1.2.1"
junit = "4.13.2"
mockitoCore = "5.18.0"
mockitoKotlin = "5.4.0"
mockk = "1.14.4"
robolectric = "4.15.1"
espressoCore = "3.6.1"


[libraries]

# Plugin dependencies for build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidxRoom" }
google-firebase-crashlytics-gradlePlugin = { group = "com.google.firebase.crashlytics", name = "com.google.firebase.crashlytics.gradle.plugin", version.ref = "googleFirebaseCrashlyticsGradle" }
google-gms-gradlePlugin = { group = "com.google.gms.google-services", name = "com.google.gms.google-services.gradle.plugin", version.ref = "googleServices" }
google-protobuf-gradlePlugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "googleProtobufGradlePlugin" }

# Dependencies used in build-logic. Might seem unused but check in files if that is the case
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestCore" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestCore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# Androidx
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-cardView = { group = "androidx.cardview", name = "cardview", version.ref = "androidxCardView" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragmentKtx" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerView" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidxLifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidxLifecycleExtension" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-vectorDrawable = { group = "androidx.vectordrawable", name = "vectordrawable-animated", version.ref = "androidxVectorDrawable" }

# Other
airbnb-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "airbnbLottie" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "googleDaggerHilt" }
google-dagger-hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "googleDaggerHilt" }
google-protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "googleProtobufRuntime" }
google-protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "googleProtobufRuntime" }


# PlayStore only. Might seem unused but check in files if that is the case
android-billingClient = { group = "com.android.billingclient", name = "billing", version.ref = "androidBillingClient" }
android-billingClient-ktx = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "androidBillingClient" }
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "googleFirebaseBom" }
google-firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "googleFirebaseCrashlytics" }
google-firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk", version.ref = "googleFirebaseCrashlytics" }
google-dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "googleDaggerHilt" }
google-userMessaging = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "googleUserMessaging" }
google-gms-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "googleGmsAds" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref = "googlePlayReview" }

# Tests only
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidxRoom" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


[plugins]

# Plugins from external providers
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidxNavigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }
androidxRoom = { id = "androidx.room", version.ref = "androidxRoom" }
googleDaggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "googleDaggerHilt" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleGms = { id = "com.google.gms.google-services", version.ref = "googleServices" }
googleCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlyticsGradle" }
googleProtobufGradle = { id = "com.google.protobuf", version.ref = "googleProtobufGradlePlugin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Plugins defined by this project
buzbuz-androidApplication = { id = "com.buzbuz.gradle.android.application", version = "unspecified" }
buzbuz-androidLibrary = { id = "com.buzbuz.gradle.android.library", version = "unspecified" }
buzbuz-androidRoom = { id = "com.buzbuz.gradle.android.room", version = "unspecified" }
buzbuz-androidUnitTest = { id = "com.buzbuz.gradle.android.unittest", version = "unspecified" }
buzbuz-androidLocalTest = { id = "com.buzbuz.gradle.android.localtest", version = "unspecified" }
buzbuz-androidSigning = { id = "com.buzbuz.gradle.android.signing", version = "unspecified" }
buzbuz-flavour = { id = "com.buzbuz.gradle.android.flavour", version = "unspecified" }
buzbuz-obfuscation = { id = "com.buzbuz.gradle.obfuscation", version = "unspecified" }
buzbuz-buildParameters = { id = "com.buzbuz.gradle.build.parameters", version = "unspecified" }
buzbuz-crashlytics = { id = "com.buzbuz.gradle.crashlytics", version = "unspecified" }
buzbuz-hilt = { id = "com.buzbuz.gradle.android.hilt", version = "unspecified" }
buzbuz-kotlinSerialization = { id = "com.buzbuz.gradle.android.kotlin.serialization", version = "unspecified" }
buzbuz-protobuf = { id = "com.buzbuz.gradle.protobuf", version = "unspecified" }
buzbuz-sourceDownload = { id = "com.buzbuz.gradle.build.sourcedl", version = "unspecified" }