name: Release PlayStore

on:
  workflow_dispatch:

jobs:
  build:
    name: Build PlayStore application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: set NDK
      shell: bash
      run: |
        set -x
        echo "ANDROID_NDK=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

    - name: Restore keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > smartautoclicker.jks.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch smartautoclicker.jks.asc > smartautoclicker/smartautoclicker.jks

    - name: Build with Gradle
      run: |
        ./gradlew \
          -PadsApplicationId="${{ secrets.ADS_APPLICATION_ID }}" \
          -PadsUnitId="${{ secrets.ADS_UNIT_ID }}" \
          -PbillingPublicKey="${{ secrets.BILLING_PUBLIC_KEY }}" \
          -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" \
          -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" \
          -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" \
          assemblePlayStoreRelease bundlePlayStoreRelease smartautoclicker:uploadCrashlyticsSymbolFilePlayStoreRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: smartautoclicker-release
        path: smartautoclicker/build/outputs/
